blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/dcdavidev/devkit/discussions
    about: Please use Discussions for proposals, questions, and ideas.
  - name: 📄 Documentation
    url: https://github.com/dcdavidev/devkit#readme
    about: Check the README and docs before opening a new issue.
